### PR TITLE
25 create add new project page

### LINKED ISSUE #53: 25 - Create add-new-project page
[ADD NEW PROJECT](https://www.figma.com/file/MpfNES0KuBUkkd0Qk4EyOc/HYF-Connect-Wireframe?node-id=282%3A321)

### PR DESCRIPTION
**Pull request by inggritenovaleta**
This is for the 'add-new-project-page'
What I have done: 

1 added multiselect-component.js
2. updated the add-new-project.html (with multiselect component)
3. updated the main-section.js (with multiselect component)
4. add createProject to the /data-access/calls.js (together with Moamin)

This version is not % done, still need to fix the connection to the backend and to add a piece of code to update the teamMembers selection from multiselect component. 

However, please take a look and give feedback for better solution.
Thank youuuu happy llamas! 🦙

### CODE REVIEW

**Comment by Moamin-AbuEwaida** [comment]
@inggritenovaleta  from the 1st sight, it looks so good :clap: and yeah still need backend connections
let me know if we can work all together to find the way to write the backend :+1:

**Comment by inggritenovaleta** [comment]
> @inggritenovaleta from the 1st sight, it looks so good 👏 and yeah still need backend connections let me know if we can work all together to find the way to write the backend 👍

thank you Moamin, tonight Rosa will help me too see it too and ill see what I can do know

**Comment by inggritenovaleta** [comment]
ALso, I have a problem, everytime I git pull origin development, I get this merging conflict. Once I was fixing it with Yoshi, and I have to accept incoming changes on the file I did not touch. 

Also today when call with Rosa, she mentioned the same problem. IS anyone know what could be the problem when git pull origin development?

**Comment by inggritenovaleta** [comment]
Hallo Happy Llamas!
I have made the revision for the frontend - backend connection. 
Now users can create a new project and click the 'save project', the input is successfully saved in the database. 

@yoshimalaise @dirk-jacobs 

thank you for the help @Moamin-AbuEwaida @RosaMoran :)

**Review by Moamin-AbuEwaida — DISMISSED** [review]
LGTM
just need to make sure that the link leads to this page added to the buttons in my profile or my projects pages

**Review by Hajir-pro — DISMISSED** [review]

**Comment by Moamin-AbuEwaida** [comment]
LGTM now :laughing:

**Pull request merged**
