### PR TITLE
23-create-contact-us-page

### LINKED ISSUE #51: 23 - Create contact-us page
[CONTACT US](https://www.figma.com/file/MpfNES0KuBUkkd0Qk4EyOc/HYF-Connect-Wireframe?node-id=22%3A96)

## `Must have` 

- [x] Footer component 
- [x] Header component 
- [x] Label with a question and Contact us
- [x] Picture 
- [x] Label or  object with client personal info and message to us 
- [x] Button submit

### PR DESCRIPTION
**Pull request by RosaMoran**
here i can not see even this letter for example

### CODE REVIEW

**Review by dirk-jacobs — CHANGES_REQUESTED** [review]
Your PR is starting to look real good.
For me, some small changes:

1. The space between the text and the part with the input fields is rather big (bit too big)
2. The column-width of the input field section is rather small (too small)
3. The submit buttons is currently in overlap with the footer
4. Why did you put the data and method section in comment. I would like to have it back !!!

Yes you can !!!

**Review by Moamin-AbuEwaida — DISMISSED** [review]
LGTM

**Comment by RosaMoran** [comment]
@dirk-jacobs 
I pushed with your last feedback.

Ready to test...! :llama: :grin: 

I'm gonna continues with `24 - Create user-profile page` 

@dirk-jacobs @Moamin-AbuEwaida @inggritenovaleta @rayanejsilva @perezrei @firity

**Comment by RosaMoran** [comment]
@dirk-jacobs
I pushed with your last feedback.

Ready to test...! :llama:

**Comment by RosaMoran** [comment]
@dirk-jacobs hey I made the changes

**Comment by RosaMoran** [comment]
@dirk-jacobs @yoshimalaise @rayanejsilva @Moamin-AbuEwaida @perezrei 
Hey Buddies, :llama: :heart:  check it please and @dirk-jacobs, I think, we did it and like we disputed then I'll improve `contact-us` but I'll make a new issue like @rayanejsilva suggested me.

Have a nice day...! :sunflower: :rose: :llama: :sun_with_face:

**Pull request merged**
