### PR TITLE
creating pages folders in client

### PR DESCRIPTION
**Pull request by perezrei**
Creating components and pages folders and subfolders in client

### CODE REVIEW

**Review by rayanejsilva — CHANGES_REQUESTED** [review]
Footer and header don’t need html file. We will import them to our html.

Is it not better to save pages and component inside of src folder? and then delete all folders will not use e.g utils, presentation, etc.?

**Comment by perezrei** [comment]
I agree to move the pages and component folders to src. We can remove the folders you commented too,  and add or remove other folders while we work. Let's wait for the other reviewer's opinion and I change whatever it's decided at the same time.

**Comment by firity** [comment]
@rayanejsilva  Do not  understand when you say we dont need the header and footer html file their
@perezrei looks good to me

**Comment by perezrei** [comment]
I moved component and pages folders. I will be waiting for the other reviewer to decide about header/footer files

**Review by rayanejsilva — APPROVED** [review]

**Review by Hajir-pro — APPROVED** [review]

**Pull request merged**
