### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by perezrei**
Update Reinaldo availability

### CODE REVIEW

**Review by bringmetheaxx — APPROVED** [review]
lgtm

**Review by inggritenovaleta — COMMENTED** [review]
Is it possible to use maybe 24h format? if not its okay :)

**Comment by Moamin-AbuEwaida** [comment]
@perezrei @bringmetheaxx 
I pushed my timing to the schedule on this branch instead of creating a new branch :+1:

**Comment by bringmetheaxx** [comment]
> @perezrei @bringmetheaxx I pushed my timing to the schedule on this branch instead of creating a new branch 👍

I just saw it and it's fine for me, but could you do it in the 24h format?

**Comment by Moamin-AbuEwaida** [comment]
> I just saw it and it's fine for me, but could you do it in the 24h format?

sure

**Comment by rayanejsilva** [comment]
@perezrei and @bringmetheaxx I pushed my availability on this branch, okay?

**Review by rayanejsilva — APPROVED** [review]

**Pull request merged**
